# Generated by Django 3.1.7 on 2021-04-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_auto_20210413_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_question',
            field=models.BooleanField(default=False),
        ),
    ]
