# Generated by Django 3.1.7 on 2021-04-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_comment_is_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_question',
            new_name='is_answer',
        ),
    ]
